import { atom } from 'recoil';

export const ProductInformation = atom({
    key: 'ProductInformation',
    default: [
        {
            product_option_id: 1,
            product_id: '0001',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 2,
            product_id: '0001',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 3,
            product_id: '0001',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 4,
            product_id: '0001',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 5,
            product_id: '0001',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 6,
            product_id: '0002',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 7,
            product_id: '0002',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 8,
            product_id: '0002',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 9,
            product_id: '0002',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 10,
            product_id: '0002',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 11,
            product_id: '0003',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 12,
            product_id: '0003',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 13,
            product_id: '0003',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 14,
            product_id: '0003',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 15,
            product_id: '0003',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 16,
            product_id: '0004',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 17,
            product_id: '0004',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 18,
            product_id: '0004',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 19,
            product_id: '0004',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 20,
            product_id: '0004',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 21,
            product_id: '0005',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 22,
            product_id: '0005',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 23,
            product_id: '0005',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 24,
            product_id: '0005',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 25,
            product_id: '0005',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 26,
            product_id: '0006',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 27,
            product_id: '0006',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 28,
            product_id: '0006',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 29,
            product_id: '0006',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 30,
            product_id: '0006',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 31,
            product_id: '0007',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 32,
            product_id: '0007',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 33,
            product_id: '0007',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 34,
            product_id: '0007',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 35,
            product_id: '0007',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 36,
            product_id: '0008',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 37,
            product_id: '0008',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 38,
            product_id: '0008',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 39,
            product_id: '0008',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 40,
            product_id: '0008',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 41,
            product_id: '0009',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 42,
            product_id: '0009',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 43,
            product_id: '0009',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 44,
            product_id: '0009',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 45,
            product_id: '0009',
            size: '2X',
            // stock: '',
        },
        {
            product_option_id: 46,
            product_id: '0010',
            size: 'S',
            // stock: '',
        },
        {
            product_option_id: 47,
            product_id: '0010',
            size: 'M',
            // stock: '',
        },
        {
            product_option_id: 48,
            product_id: '0010',
            size: 'L',
            // stock: '',
        },
        {
            product_option_id: 49,
            product_id: '0010',
            size: 'XL',
            // stock: '',
        },
        {
            product_option_id: 50,
            product_id: '0010',
            size: '2X',
            // stock: '',
        },
    ],
});
