import { atom } from 'recoil';

export interface ProductInformationItem {
    product_option_id: number;
    product_id: number;
    size: string;
    stock: number;
}

export const ProductInformation = atom<ProductInformationItem[]>({
    key: 'ProductInformation',
    default: [
        {
            product_option_id: 1,
            product_id: 1,
            size: 'S',
            stock: 0,
        },
        {
            product_option_id: 2,
            product_id: 1,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 3,
            product_id: 1,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 4,
            product_id: 1,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 5,
            product_id: 1,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 6,
            product_id: 2,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 7,
            product_id: 2,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 8,
            product_id: 2,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 9,
            product_id: 2,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 10,
            product_id: 2,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 11,
            product_id: 3,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 12,
            product_id: 3,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 13,
            product_id: 3,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 14,
            product_id: 3,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 15,
            product_id: 3,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 16,
            product_id: 4,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 17,
            product_id: 4,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 18,
            product_id: 4,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 19,
            product_id: 4,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 20,
            product_id: 4,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 21,
            product_id: 5,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 22,
            product_id: 5,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 23,
            product_id: 5,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 24,
            product_id: 5,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 25,
            product_id: 5,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 26,
            product_id: 6,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 27,
            product_id: 6,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 28,
            product_id: 6,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 29,
            product_id: 6,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 30,
            product_id: 6,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 31,
            product_id: 7,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 32,
            product_id: 7,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 33,
            product_id: 7,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 34,
            product_id: 7,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 35,
            product_id: 7,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 36,
            product_id: 8,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 37,
            product_id: 8,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 38,
            product_id: 8,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 39,
            product_id: 8,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 40,
            product_id: 8,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 41,
            product_id: 9,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 42,
            product_id: 9,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 43,
            product_id: 9,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 44,
            product_id: 9,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 45,
            product_id: 9,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 46,
            product_id: 10,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 47,
            product_id: 10,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 48,
            product_id: 10,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 49,
            product_id: 10,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 50,
            product_id: 10,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 51,
            product_id: 11,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 52,
            product_id: 11,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 53,
            product_id: 11,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 54,
            product_id: 11,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 55,
            product_id: 11,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 56,
            product_id: 12,
            size: '28',
            stock: 5,
        },
        {
            product_option_id: 57,
            product_id: 12,
            size: '29',
            stock: 5,
        },
        {
            product_option_id: 58,
            product_id: 12,
            size: '30',
            stock: 5,
        },
        {
            product_option_id: 59,
            product_id: 12,
            size: '31',
            stock: 5,
        },
        {
            product_option_id: 60,
            product_id: 12,
            size: '32',
            stock: 5,
        },
        {
            product_option_id: 61,
            product_id: 13,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 62,
            product_id: 13,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 63,
            product_id: 13,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 64,
            product_id: 13,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 65,
            product_id: 13,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 66,
            product_id: 14,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 67,
            product_id: 14,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 68,
            product_id: 14,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 69,
            product_id: 14,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 70,
            product_id: 14,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 71,
            product_id: 15,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 72,
            product_id: 15,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 73,
            product_id: 15,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 74,
            product_id: 15,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 75,
            product_id: 15,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 76,
            product_id: 16,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 77,
            product_id: 16,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 78,
            product_id: 16,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 79,
            product_id: 16,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 80,
            product_id: 16,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 81,
            product_id: 17,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 82,
            product_id: 17,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 83,
            product_id: 17,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 84,
            product_id: 17,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 85,
            product_id: 17,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 86,
            product_id: 18,
            size: 'S',
            stock: 5,
        },
        {
            product_option_id: 87,
            product_id: 18,
            size: 'M',
            stock: 5,
        },
        {
            product_option_id: 88,
            product_id: 18,
            size: 'L',
            stock: 5,
        },
        {
            product_option_id: 89,
            product_id: 18,
            size: 'XL',
            stock: 5,
        },
        {
            product_option_id: 90,
            product_id: 18,
            size: '2X',
            stock: 5,
        },
        {
            product_option_id: 91,
            product_id: 19,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 92,
            product_id: 19,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 93,
            product_id: 19,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 94,
            product_id: 19,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 95,
            product_id: 19,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 96,
            product_id: 20,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 97,
            product_id: 20,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 98,
            product_id: 20,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 99,
            product_id: 20,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 100,
            product_id: 20,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 101,
            product_id: 21,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 102,
            product_id: 21,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 103,
            product_id: 21,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 104,
            product_id: 21,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 105,
            product_id: 21,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 106,
            product_id: 22,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 107,
            product_id: 22,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 108,
            product_id: 22,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 109,
            product_id: 22,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 110,
            product_id: 22,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 111,
            product_id: 23,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 112,
            product_id: 23,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 113,
            product_id: 23,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 114,
            product_id: 23,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 115,
            product_id: 23,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 116,
            product_id: 24,
            size: '240',
            stock: 5,
        },
        {
            product_option_id: 117,
            product_id: 24,
            size: '250',
            stock: 5,
        },
        {
            product_option_id: 118,
            product_id: 24,
            size: '260',
            stock: 5,
        },
        {
            product_option_id: 119,
            product_id: 24,
            size: '270',
            stock: 5,
        },
        {
            product_option_id: 120,
            product_id: 24,
            size: '280',
            stock: 5,
        },
        {
            product_option_id: 121,
            product_id: 25,
            size: 'free',
            stock: 5,
        },
        {
            product_option_id: 122,
            product_id: 26,
            size: 'free',
            stock: 5,
        },
        {
            product_option_id: 123,
            product_id: 27,
            size: 'free',
            stock: 5,
        },
        {
            product_option_id: 124,
            product_id: 28,
            size: 'free',
            stock: 5,
        },
        {
            product_option_id: 125,
            product_id: 29,
            size: 'free',
            stock: 5,
        },
        {
            product_option_id: 126,
            product_id: 30,
            size: 'free',
            stock: 5,
        },
    ],
});
